import Key from "react-native-neat-date-picker/src/components/Key";

export const carData = [
  {
    carname: "Mercedes-Benz",
    rate: 50,
    pictureurl: "../../assets/car1.jpg",
    star: 4.5,
    pickup: "Hemel Hempstead",
    notes: ["Car Disinfected before each trip", "Free Cancellation"],
  },
  {
    carname: "Audi",
    rate: 65,
    pictureurl: "../../assets/car2.jpg",
    star: 3,
    pickup: "Milton Keynes",
    notes: ["Coffee Stains In Rear", "Free Cancellation"],
  },
  {
    carname: "BMW M4",
    rate: 70,
    pictureurl: "../../assets/car3.jpg",
    star: 5,
    pickup: "Bedfordshire",
    notes: ["Needs Replacement Wheel", "Free Cancellation"],
  },
  {
    carname: "Ford Fiesta ST",
    rate: 50,
    pictureurl: "../../assets/car4.jpg",
    star: 3,
    pickup: "Hertfordshire",
    notes: ["Fully Working Air Conditioning", "Free Cancellation"],
  },
  {
    carname: "Ford Puma",
    rate: 65,
    pictureurl: "../../assets/car5.jpg",
    star: 5,
    pickup: "London",
    notes: ["Minor accident repair work done", "Free Cancellation"],
  },
  {
    carname: "Nissan Qashqai",
    rate: 70,
    pictureurl: "../../assets/car6.jpg",
    star: 5,
    pickup: "Dunstable",
    notes: ["Doesn't have full service history", "Free Cancellation"],
  },
  {
    carname: "Volkswagen Arteon",
    rate: 80,
    pictureurl: "../../assets/car7.jpg",
    star: 5,
    pickup: "Houten Regis",
    notes: ["Stage One Tuning Kit Applied", "Free Cancellation"],
  },
  {
    carname: "Volkswagen Polo",
    rate: 75,
    pictureurl: "../../assets/car8.jpg",
    star: 4,
    pickup: "Hemel Hempstead",
    notes: ["Has lovely suspension", "Free Cancellation"],
  },
];
